///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TGNOS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteIndividu recording.
    /// </summary>
    [TestModule("d2bfb565-1997-4de5-ab34-0af5bb7cf1bb", ModuleType.Recording, 1)]
    public partial class DeleteIndividu : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TGNOSRepository repository.
        /// </summary>
        public static TGNOSRepository repo = TGNOSRepository.Instance;

        static DeleteIndividu instance = new DeleteIndividu();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteIndividu()
        {
            varRRNr = "55010116297";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteIndividu Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varRRNr.
        /// </summary>
        [TestVariable("8762e184-ff2f-4bc9-b72c-61f545b1d0dd")]
        public string varRRNr
        {
            get { return repo.varRRNr; }
            set { repo.varRRNr = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // Start Individu wissen
            Report.Log(ReportLevel.Info, "Section", "Start Individu wissen", new RecordItemIndex(0));
            
            repo.TGNOS.Individu.Click("44;13");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TgnosClientComponentsWinTgnosApp.Open' at 50;5.", repo.TgnosClientComponentsWinTgnosApp.OpenInfo, new RecordItemIndex(2));
            repo.TgnosClientComponentsWinTgnosApp.Open.Click("50;5");
            
            addRRNr(repo.TGNOS.OpzoekenIndividuStart.INSZNummerInfo);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TGNOS.OpzoekenIndividuStart.INSZNummer' at 4;9.", repo.TGNOS.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(4));
            //repo.TGNOS.OpzoekenIndividuStart.INSZNummer.Click("4;9");
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Left}{Left}' with focus on 'TGNOS.OpzoekenIndividuStart.INSZNummer'.", repo.TGNOS.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(5));
            //repo.TGNOS.OpzoekenIndividuStart.INSZNummer.PressKeys("{Left}{Left}");
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Left}' with focus on 'TGNOS.OpzoekenIndividuStart.INSZNummer'.", repo.TGNOS.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(6));
            //repo.TGNOS.OpzoekenIndividuStart.INSZNummer.PressKeys("{Left}");
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Left up}' with focus on 'TGNOS.OpzoekenIndividuStart.INSZNummer'.", repo.TGNOS.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(7));
            //repo.TGNOS.OpzoekenIndividuStart.INSZNummer.PressKeys("{Left up}");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TGNOS.OpzoekenIndividuStart.BtnOpzoeken' at 17;11.", repo.TGNOS.OpzoekenIndividuStart.BtnOpzoekenInfo, new RecordItemIndex(8));
            repo.TGNOS.OpzoekenIndividuStart.BtnOpzoeken.Click("17;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'TGNOS.OpzoekenIndividuStart.DtgrdZoekResultaat' at 21;26.", repo.TGNOS.OpzoekenIndividuStart.DtgrdZoekResultaatInfo, new RecordItemIndex(9));
            repo.TGNOS.OpzoekenIndividuStart.DtgrdZoekResultaat.DoubleClick("21;26");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TGNOS.TbpgBasisInformatie.BtnIndividuWissen' at 43;9.", repo.TGNOS.TbpgBasisInformatie.BtnIndividuWissenInfo, new RecordItemIndex(10));
            repo.TGNOS.TbpgBasisInformatie.BtnIndividuWissen.Click("43;9");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'enter{Return}'.", new RecordItemIndex(11));
            Keyboard.Press("enter{Return}");
            
            Ranorex.AutomationHelpers.UserCodeCollections.WebLibrary.GetHttpStatusCode("https://jsonplaceholder.typicode.com/posts");
            
            // Einde Individu wissen
            Report.Log(ReportLevel.Info, "Section", "Einde Individu wissen", new RecordItemIndex(13));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
