///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TGNOS
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("20151dfa-72bd-43af-8998-57b78ec525b5", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TGNOSRepository repository.
        /// </summary>
        public static TGNOSRepository repo = TGNOSRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            repo.ApplicationUnderTest.Individu.Click("44;13");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TgnosClientComponentsWinTgnosApp.Open' at 50;5.", repo.TgnosClientComponentsWinTgnosApp.OpenInfo, new RecordItemIndex(1));
            repo.TgnosClientComponentsWinTgnosApp.Open.Click("50;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer' at 4;9.", repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer.Click("4;9");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Left}{Left}' with focus on 'ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer'.", repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer.PressKeys("{Left}{Left}");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Left}' with focus on 'ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer'.", repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer.PressKeys("{Left}");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Left up}' with focus on 'ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer'.", repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer.PressKeys("{Left up}");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '55010116297' with focus on 'ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer'.", repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummerInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer.PressKeys("55010116297");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OpzoekenIndividuStart.BtnOpzoeken' at 17;11.", repo.ApplicationUnderTest.OpzoekenIndividuStart.BtnOpzoekenInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.BtnOpzoeken.Click("17;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.OpzoekenIndividuStart.DtgrdZoekResultaat' at 21;26.", repo.ApplicationUnderTest.OpzoekenIndividuStart.DtgrdZoekResultaatInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.DtgrdZoekResultaat.DoubleClick("21;26");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgBasisInformatie.BtnIndividuWissen' at 43;9.", repo.ApplicationUnderTest.TbpgBasisInformatie.BtnIndividuWissenInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.TbpgBasisInformatie.BtnIndividuWissen.Click("43;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ButtonOK2' at 36;10.", repo.ApplicationUnderTest.ButtonOK2Info, new RecordItemIndex(10));
            repo.ApplicationUnderTest.ButtonOK2.Click("36;10");
            
            // Einde Individu wissen
            Report.Log(ReportLevel.Info, "Section", "Einde Individu wissen", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OpzoekenIndividuStart.BtnOpzoeken' at 17;11.", repo.ApplicationUnderTest.OpzoekenIndividuStart.BtnOpzoekenInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.BtnOpzoeken.Click("17;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OpzoekenIndividuStart.BtnNieuw' at 28;11.", repo.ApplicationUnderTest.OpzoekenIndividuStart.BtnNieuwInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.OpzoekenIndividuStart.BtnNieuw.Click("28;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgBasisInformatie.Familienaam' at 61;13.", repo.ApplicationUnderTest.TbpgBasisInformatie.FamilienaamInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.TbpgBasisInformatie.Familienaam.Click("61;13");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'ApplicationUnderTest.TbpgBasisInformatie.Familienaam'.", repo.ApplicationUnderTest.TbpgBasisInformatie.FamilienaamInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.TbpgBasisInformatie.Familienaam.PressKeys("test");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgBasisInformatie.Voornaam1' at 55;6.", repo.ApplicationUnderTest.TbpgBasisInformatie.Voornaam1Info, new RecordItemIndex(16));
            repo.ApplicationUnderTest.TbpgBasisInformatie.Voornaam1.Click("55;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ranorex' with focus on 'ApplicationUnderTest.TbpgBasisInformatie.Voornaam1'.", repo.ApplicationUnderTest.TbpgBasisInformatie.Voornaam1Info, new RecordItemIndex(17));
            repo.ApplicationUnderTest.TbpgBasisInformatie.Voornaam1.PressKeys("ranorex");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1' at 1;8.", repo.ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1Info, new RecordItemIndex(18));
            repo.ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1.Click("1;8");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '5501011' with focus on 'ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1'.", repo.ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1Info, new RecordItemIndex(19));
            repo.ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1.PressKeys("5501011");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '6297' with focus on 'ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1'.", repo.ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1Info, new RecordItemIndex(20));
            repo.ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1.PressKeys("6297");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgBasisInformatie.Geboorteplaats' at 16;7.", repo.ApplicationUnderTest.TbpgBasisInformatie.GeboorteplaatsInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.TbpgBasisInformatie.Geboorteplaats.Click("16;7");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'mEchelen' with focus on 'ApplicationUnderTest.TbpgBasisInformatie.Geboorteplaats'.", repo.ApplicationUnderTest.TbpgBasisInformatie.GeboorteplaatsInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.TbpgBasisInformatie.Geboorteplaats.PressKeys("mEchelen");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgBasisInformatie.TextAsterisk' at 31;6.", repo.ApplicationUnderTest.TbpgBasisInformatie.TextAsteriskInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.TbpgBasisInformatie.TextAsterisk.Click("31;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '01011955' with focus on 'ApplicationUnderTest.TbpgBasisInformatie.TextAsterisk'.", repo.ApplicationUnderTest.TbpgBasisInformatie.TextAsteriskInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.TbpgBasisInformatie.TextAsterisk.PressKeys("01011955");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox' at 41;7.", repo.ApplicationUnderTest.Individu1.CboComboBoxInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.Individu1.CboComboBox.Click("41;7");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Belgie' at 28;5.", repo.List1000.BelgieInfo, new RecordItemIndex(26));
            repo.List1000.Belgie.Click("28;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox1' at 64;14.", repo.ApplicationUnderTest.Individu1.CboComboBox1Info, new RecordItemIndex(27));
            repo.ApplicationUnderTest.Individu1.CboComboBox1.Click("64;14");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItemMan' at 57;6.", repo.List1000.ListItemManInfo, new RecordItemIndex(28));
            repo.List1000.ListItemMan.Click("57;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.Geldig' at 91;6.", repo.ApplicationUnderTest.Individu1.GeldigInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.Individu1.Geldig.Click("91;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.Geldig' at 91;10.", repo.ApplicationUnderTest.Individu1.GeldigInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.Individu1.Geldig.Click("91;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.BtnOpslaan' at 59;13.", repo.ApplicationUnderTest.Individu1.BtnOpslaanInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.Individu1.BtnOpslaan.Click("59;13");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='\t\tHet opslaan is voltooid.') on item 'ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooid'.", repo.ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooidInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooidInfo, "Text", "\t\tHet opslaan is voltooid.");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.Signalitiek' at 68;12.", repo.ApplicationUnderTest.Individu1.SignalitiekInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.Individu1.Signalitiek.Click("68;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox2' at 84;6.", repo.ApplicationUnderTest.Individu1.CboComboBox2Info, new RecordItemIndex(34));
            repo.ApplicationUnderTest.Individu1.CboComboBox2.Click("84;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Belgische' at 48;5.", repo.List1000.BelgischeInfo, new RecordItemIndex(35));
            repo.List1000.Belgische.Click("48;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgSignalitiek.GsmNr' at 40;13.", repo.ApplicationUnderTest.TbpgSignalitiek.GsmNrInfo, new RecordItemIndex(36));
            repo.ApplicationUnderTest.TbpgSignalitiek.GsmNr.Click("40;13");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0472611353' with focus on 'ApplicationUnderTest.TbpgSignalitiek.GsmNr'.", repo.ApplicationUnderTest.TbpgSignalitiek.GsmNrInfo, new RecordItemIndex(37));
            repo.ApplicationUnderTest.TbpgSignalitiek.GsmNr.PressKeys("0472611353");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgSignalitiek.TelefoonnrThuis' at 35;7.", repo.ApplicationUnderTest.TbpgSignalitiek.TelefoonnrThuisInfo, new RecordItemIndex(38));
            repo.ApplicationUnderTest.TbpgSignalitiek.TelefoonnrThuis.Click("35;7");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '015800100' with focus on 'ApplicationUnderTest.TbpgSignalitiek.TelefoonnrThuis'.", repo.ApplicationUnderTest.TbpgSignalitiek.TelefoonnrThuisInfo, new RecordItemIndex(39));
            repo.ApplicationUnderTest.TbpgSignalitiek.TelefoonnrThuis.PressKeys("015800100");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.Text' at 28;8.", repo.ApplicationUnderTest.Individu1.TextInfo, new RecordItemIndex(40));
            repo.ApplicationUnderTest.Individu1.Text.Click("28;8");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tgnos.test@agilitasgroup.be' with focus on 'ApplicationUnderTest.Individu1.Text'.", repo.ApplicationUnderTest.Individu1.TextInfo, new RecordItemIndex(41));
            repo.ApplicationUnderTest.Individu1.Text.PressKeys("tgnos.test@agilitasgroup.be");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgSignalitiek.Text1' at 132;7.", repo.ApplicationUnderTest.TbpgSignalitiek.Text1Info, new RecordItemIndex(42));
            repo.ApplicationUnderTest.TbpgSignalitiek.Text1.Click("132;7");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'stationsstraat' with focus on 'ApplicationUnderTest.TbpgSignalitiek.TxtStraat1'.", repo.ApplicationUnderTest.TbpgSignalitiek.TxtStraat1Info, new RecordItemIndex(43));
            repo.ApplicationUnderTest.TbpgSignalitiek.TxtStraat1.PressKeys("stationsstraat");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgSignalitiek.Straat' at 52;6.", repo.ApplicationUnderTest.TbpgSignalitiek.StraatInfo, new RecordItemIndex(44));
            repo.ApplicationUnderTest.TbpgSignalitiek.Straat.Click("52;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '120' with focus on 'ApplicationUnderTest.TbpgSignalitiek.Straat'.", repo.ApplicationUnderTest.TbpgSignalitiek.StraatInfo, new RecordItemIndex(45));
            repo.ApplicationUnderTest.TbpgSignalitiek.Straat.PressKeys("120");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgSignalitiek.Text2' at 38;6.", repo.ApplicationUnderTest.TbpgSignalitiek.Text2Info, new RecordItemIndex(46));
            repo.ApplicationUnderTest.TbpgSignalitiek.Text2.Click("38;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2800' with focus on 'ApplicationUnderTest.TbpgSignalitiek.Text2'.", repo.ApplicationUnderTest.TbpgSignalitiek.Text2Info, new RecordItemIndex(47));
            repo.ApplicationUnderTest.TbpgSignalitiek.Text2.PressKeys("2800");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CbxCheckBox' at 5;12.", repo.ApplicationUnderTest.Individu1.CbxCheckBoxInfo, new RecordItemIndex(48));
            repo.ApplicationUnderTest.Individu1.CbxCheckBox.Click("5;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1' at 27;8.", repo.ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1Info, new RecordItemIndex(49));
            repo.ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1.Click("27;8");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '3112' with focus on 'ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1'.", repo.ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1Info, new RecordItemIndex(50));
            repo.ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1.PressKeys("3112");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2999' with focus on 'ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1'.", repo.ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1Info, new RecordItemIndex(51));
            repo.ApplicationUnderTest.TbpgSignalitiek.TextAsterisk1.PressKeys("2999");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.BtnOpslaan' at 65;19.", repo.ApplicationUnderTest.Individu1.BtnOpslaanInfo, new RecordItemIndex(52));
            repo.ApplicationUnderTest.Individu1.BtnOpslaan.Click("65;19");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Het opslaan is voltooid.') on item 'ApplicationUnderTest.Individu1.HetOpslaanIsVoltooid'.", repo.ApplicationUnderTest.Individu1.HetOpslaanIsVoltooidInfo, new RecordItemIndex(53));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Individu1.HetOpslaanIsVoltooidInfo, "Text", "Het opslaan is voltooid.");
            
            // Start Fiscaal en Verloning Tab
            Report.Log(ReportLevel.Info, "Section", "Start Fiscaal en Verloning Tab", new RecordItemIndex(54));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.FiscaalVerloning' at 63;17.", repo.ApplicationUnderTest.Individu1.FiscaalVerloningInfo, new RecordItemIndex(55));
            repo.ApplicationUnderTest.Individu1.FiscaalVerloning.Click("63;17");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox3' at 211;10.", repo.ApplicationUnderTest.Individu1.CboComboBox3Info, new RecordItemIndex(56));
            repo.ApplicationUnderTest.Individu1.CboComboBox3.Click("211;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Gehuwd' at 63;6.", repo.List1000.GehuwdInfo, new RecordItemIndex(57));
            repo.List1000.Gehuwd.Click("63;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.TextAsterisk1' at 3;5.", repo.ApplicationUnderTest.Individu1.TextAsterisk1Info, new RecordItemIndex(58));
            repo.ApplicationUnderTest.Individu1.TextAsterisk1.Click("3;5");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '03052019' with focus on 'ApplicationUnderTest.Individu1.TextAsterisk1'.", repo.ApplicationUnderTest.Individu1.TextAsterisk1Info, new RecordItemIndex(59));
            repo.ApplicationUnderTest.Individu1.TextAsterisk1.PressKeys("03052019");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.TextAsterisk2' at Center.", repo.ApplicationUnderTest.Individu1.TextAsterisk2Info, new RecordItemIndex(60));
            repo.ApplicationUnderTest.Individu1.TextAsterisk2.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '03052019' with focus on 'ApplicationUnderTest.Individu1.TextAsterisk2'.", repo.ApplicationUnderTest.Individu1.TextAsterisk2Info, new RecordItemIndex(61));
            repo.ApplicationUnderTest.Individu1.TextAsterisk2.PressKeys("03052019");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.NaamEchtgenoOTE' at 62;10.", repo.ApplicationUnderTest.Individu1.NaamEchtgenoOTEInfo, new RecordItemIndex(62));
            repo.ApplicationUnderTest.Individu1.NaamEchtgenoOTE.Click("62;10");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test'.", new RecordItemIndex(63));
            Keyboard.Press("test");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.VoornaamEchtgenoOTE' at 18;7.", repo.ApplicationUnderTest.Individu1.VoornaamEchtgenoOTEInfo, new RecordItemIndex(64));
            repo.ApplicationUnderTest.Individu1.VoornaamEchtgenoOTE.Click("18;7");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'ApplicationUnderTest.Individu1.VoornaamEchtgenoOTE'.", repo.ApplicationUnderTest.Individu1.VoornaamEchtgenoOTEInfo, new RecordItemIndex(65));
            repo.ApplicationUnderTest.Individu1.VoornaamEchtgenoOTE.PressKeys("test");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.TextAsterisk' at 69;7.", repo.ApplicationUnderTest.Individu1.TextAsteriskInfo, new RecordItemIndex(66));
            repo.ApplicationUnderTest.Individu1.TextAsterisk.Click("69;7");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '010119'.", new RecordItemIndex(67));
            Keyboard.Press("010119");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'ApplicationUnderTest.Individu1.TextAsterisk'.", repo.ApplicationUnderTest.Individu1.TextAsteriskInfo, new RecordItemIndex(68));
            repo.ApplicationUnderTest.Individu1.TextAsterisk.PressKeys("50");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox4' at 83;9.", repo.ApplicationUnderTest.Individu1.CboComboBox4Info, new RecordItemIndex(69));
            repo.ApplicationUnderTest.Individu1.CboComboBox4.Click("83;9");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.EchtgenootMetBeroepsinkomen' at 85;4.", repo.List1000.EchtgenootMetBeroepsinkomenInfo, new RecordItemIndex(70));
            repo.List1000.EchtgenootMetBeroepsinkomen.Click("85;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox5' at 93;14.", repo.ApplicationUnderTest.Individu1.CboComboBox5Info, new RecordItemIndex(71));
            repo.ApplicationUnderTest.Individu1.CboComboBox5.Click("93;14");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Arbeider' at 54;4.", repo.List1000.ArbeiderInfo, new RecordItemIndex(72));
            repo.List1000.Arbeider.Click("54;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox6' at 65;16.", repo.ApplicationUnderTest.Individu1.CboComboBox6Info, new RecordItemIndex(73));
            repo.ApplicationUnderTest.Individu1.CboComboBox6.Click("65;16");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Bankrekening' at 60;5.", repo.List1000.BankrekeningInfo, new RecordItemIndex(74));
            repo.List1000.Bankrekening.Click("60;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.IBAN' at 43;8.", repo.ApplicationUnderTest.Individu1.IBANInfo, new RecordItemIndex(75));
            repo.ApplicationUnderTest.Individu1.IBAN.Click("43;8");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'be26733024201429' with focus on 'ApplicationUnderTest.Individu1.IBAN'.", repo.ApplicationUnderTest.Individu1.IBANInfo, new RecordItemIndex(76));
            repo.ApplicationUnderTest.Individu1.IBAN.PressKeys("be26733024201429");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CbxCheckBox1' at 8;12.", repo.ApplicationUnderTest.Individu1.CbxCheckBox1Info, new RecordItemIndex(77));
            repo.ApplicationUnderTest.Individu1.CbxCheckBox1.Click("8;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.TextPercentInvaliditeitIndividu' at 64;9.", repo.ApplicationUnderTest.Individu1.TextPercentInvaliditeitIndividuInfo, new RecordItemIndex(78));
            repo.ApplicationUnderTest.Individu1.TextPercentInvaliditeitIndividu.Click("64;9");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '20' with focus on 'ApplicationUnderTest.Individu1.TextPercentInvaliditeitIndividu'.", repo.ApplicationUnderTest.Individu1.TextPercentInvaliditeitIndividuInfo, new RecordItemIndex(79));
            repo.ApplicationUnderTest.Individu1.TextPercentInvaliditeitIndividu.PressKeys("20");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CbxCheckBox2' at 10;12.", repo.ApplicationUnderTest.Individu1.CbxCheckBox2Info, new RecordItemIndex(80));
            repo.ApplicationUnderTest.Individu1.CbxCheckBox2.Click("10;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.AantPersTenLasteValide' at 81;6.", repo.ApplicationUnderTest.Individu1.AantPersTenLasteValideInfo, new RecordItemIndex(81));
            repo.ApplicationUnderTest.Individu1.AantPersTenLasteValide.Click("81;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Individu1.AantPersTenLasteValide'.", repo.ApplicationUnderTest.Individu1.AantPersTenLasteValideInfo, new RecordItemIndex(82));
            repo.ApplicationUnderTest.Individu1.AantPersTenLasteValide.PressKeys("1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.AantPersTenLasteValide' at 81;6.", repo.ApplicationUnderTest.Individu1.AantPersTenLasteValideInfo, new RecordItemIndex(83));
            repo.ApplicationUnderTest.Individu1.AantPersTenLasteValide.Click("81;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Individu1.AantPersTenLasteValide'.", repo.ApplicationUnderTest.Individu1.AantPersTenLasteValideInfo, new RecordItemIndex(84));
            repo.ApplicationUnderTest.Individu1.AantPersTenLasteValide.PressKeys("1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.Individu1.AantPersTenLasteAndersvalide' at 38;5.", repo.ApplicationUnderTest.Individu1.AantPersTenLasteAndersvalideInfo, new RecordItemIndex(85));
            repo.ApplicationUnderTest.Individu1.AantPersTenLasteAndersvalide.MoveTo("38;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.Individu1.AantPersTenLasteAndersvalide' at 80;5.", repo.ApplicationUnderTest.Individu1.AantPersTenLasteAndersvalideInfo, new RecordItemIndex(86));
            repo.ApplicationUnderTest.Individu1.AantPersTenLasteAndersvalide.MoveTo("80;5");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Individu1.TxtTextBox'.", repo.ApplicationUnderTest.Individu1.TxtTextBoxInfo, new RecordItemIndex(87));
            repo.ApplicationUnderTest.Individu1.TxtTextBox.PressKeys("1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.Aant65PlusPersTenLasteValide' at 78;7.", repo.ApplicationUnderTest.Individu1.Aant65PlusPersTenLasteValideInfo, new RecordItemIndex(88));
            repo.ApplicationUnderTest.Individu1.Aant65PlusPersTenLasteValide.Click("78;7");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Individu1.Aant65PlusPersTenLasteValide'.", repo.ApplicationUnderTest.Individu1.Aant65PlusPersTenLasteValideInfo, new RecordItemIndex(89));
            repo.ApplicationUnderTest.Individu1.Aant65PlusPersTenLasteValide.PressKeys("1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalide' at 77;10.", repo.ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalideInfo, new RecordItemIndex(90));
            repo.ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalide.MoveTo("77;10");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalide' at 77;10.", repo.ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalideInfo, new RecordItemIndex(91));
            repo.ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalide.MoveTo("77;10");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalide'.", repo.ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalideInfo, new RecordItemIndex(92));
            repo.ApplicationUnderTest.Individu1.Aant65PlusTenLasteAndersvalide.PressKeys("1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.AantKindTenLasteValide' at 76;6.", repo.ApplicationUnderTest.Individu1.AantKindTenLasteValideInfo, new RecordItemIndex(93));
            repo.ApplicationUnderTest.Individu1.AantKindTenLasteValide.Click("76;6");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Individu1.AantKindTenLasteValide'.", repo.ApplicationUnderTest.Individu1.AantKindTenLasteValideInfo, new RecordItemIndex(94));
            repo.ApplicationUnderTest.Individu1.AantKindTenLasteValide.PressKeys("1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.AantKindTenLasteAndersvalide' at 75;9.", repo.ApplicationUnderTest.Individu1.AantKindTenLasteAndersvalideInfo, new RecordItemIndex(95));
            repo.ApplicationUnderTest.Individu1.AantKindTenLasteAndersvalide.Click("75;9");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'ApplicationUnderTest.Individu1.AantKindTenLasteAndersvalide'.", repo.ApplicationUnderTest.Individu1.AantKindTenLasteAndersvalideInfo, new RecordItemIndex(96));
            repo.ApplicationUnderTest.Individu1.AantKindTenLasteAndersvalide.PressKeys("1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox7' at 69;5.", repo.ApplicationUnderTest.Individu1.CboComboBox7Info, new RecordItemIndex(97));
            repo.ApplicationUnderTest.Individu1.CboComboBox7.Click("69;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.ListItem5deEn6deMiddelbaarASO' at 72;3.", repo.List1000.ListItem5deEn6deMiddelbaarASOInfo, new RecordItemIndex(98));
            repo.List1000.ListItem5deEn6deMiddelbaarASO.Click("72;3");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.BtnOpslaan' at 37;10.", repo.ApplicationUnderTest.Individu1.BtnOpslaanInfo, new RecordItemIndex(99));
            repo.ApplicationUnderTest.Individu1.BtnOpslaan.Click("37;10");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='\t\tHet opslaan is voltooid.') on item 'ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooid'.", repo.ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooidInfo, new RecordItemIndex(100));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooidInfo, "Text", "\t\tHet opslaan is voltooid.");
            
            // Start Aspiraties
            Report.Log(ReportLevel.Info, "Section", "Start Aspiraties", new RecordItemIndex(101));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.Aspiraties' at 69;16.", repo.ApplicationUnderTest.Individu1.AspiratiesInfo, new RecordItemIndex(102));
            repo.ApplicationUnderTest.Individu1.Aspiraties.Click("69;16");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.BtnNieuwBeroep' at 42;7.", repo.ApplicationUnderTest.Individu1.BtnNieuwBeroepInfo, new RecordItemIndex(103));
            repo.ApplicationUnderTest.Individu1.BtnNieuwBeroep.Click("42;7");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TgnosDetailIndividu' at 262;7.", repo.ApplicationUnderTest.TgnosDetailIndividuInfo, new RecordItemIndex(104));
            repo.ApplicationUnderTest.TgnosDetailIndividu.Click("262;7");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Text1' at 20;9.", repo.ApplicationUnderTest.Text1Info, new RecordItemIndex(105));
            repo.ApplicationUnderTest.Text1.Click("20;9");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '*HUISHOUD*' with focus on 'ApplicationUnderTest.Text1'.", repo.ApplicationUnderTest.Text1Info, new RecordItemIndex(106));
            repo.ApplicationUnderTest.Text1.PressKeys("*HUISHOUD*");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnZoeken' at 9;5.", repo.ApplicationUnderTest.BtnZoekenInfo, new RecordItemIndex(107));
            repo.ApplicationUnderTest.BtnZoeken.Click("9;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TreeItem93399HuishoudelijkeHulp' at 73;7.", repo.ApplicationUnderTest.TreeItem93399HuishoudelijkeHulpInfo, new RecordItemIndex(108));
            repo.ApplicationUnderTest.TreeItem93399HuishoudelijkeHulp.Click("73;7");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest.TreeItem93399HuishoudelijkeHulp' at 17;1.", repo.ApplicationUnderTest.TreeItem93399HuishoudelijkeHulpInfo, new RecordItemIndex(109));
            repo.ApplicationUnderTest.TreeItem93399HuishoudelijkeHulp.DoubleClick("17;1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnOk' at 38;10.", repo.ApplicationUnderTest.BtnOkInfo, new RecordItemIndex(110));
            repo.ApplicationUnderTest.BtnOk.Click("38;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.MobiliteitStraalKm' at 121;7.", repo.ApplicationUnderTest.Individu1.MobiliteitStraalKmInfo, new RecordItemIndex(111));
            repo.ApplicationUnderTest.Individu1.MobiliteitStraalKm.Click("121;7");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '20' with focus on 'ApplicationUnderTest.Individu1.MobiliteitStraalKm'.", repo.ApplicationUnderTest.Individu1.MobiliteitStraalKmInfo, new RecordItemIndex(112));
            repo.ApplicationUnderTest.Individu1.MobiliteitStraalKm.PressKeys("20");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox8' at 146;10.", repo.ApplicationUnderTest.Individu1.CboComboBox8Info, new RecordItemIndex(113));
            repo.ApplicationUnderTest.Individu1.CboComboBox8.Click("146;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Auto' at 86;6.", repo.List1000.AutoInfo, new RecordItemIndex(114));
            repo.List1000.Auto.Click("86;6");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CbxCheckBox3' at 6;11.", repo.ApplicationUnderTest.Individu1.CbxCheckBox3Info, new RecordItemIndex(115));
            repo.ApplicationUnderTest.Individu1.CbxCheckBox3.Click("6;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.Individu1.CbxCheckBox4' at 4;6.", repo.ApplicationUnderTest.Individu1.CbxCheckBox4Info, new RecordItemIndex(116));
            repo.ApplicationUnderTest.Individu1.CbxCheckBox4.MoveTo("4;6");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.Individu1.CbxCheckBox4' at 12;-2.", repo.ApplicationUnderTest.Individu1.CbxCheckBox4Info, new RecordItemIndex(117));
            repo.ApplicationUnderTest.Individu1.CbxCheckBox4.MoveTo("12;-2");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.Individu1.GrpAspiraties' at 653;311.", repo.ApplicationUnderTest.Individu1.GrpAspiratiesInfo, new RecordItemIndex(118));
            repo.ApplicationUnderTest.Individu1.GrpAspiraties.MoveTo("653;311");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.TgnosDetailIndividu' at 427;5.", repo.ApplicationUnderTest.TgnosDetailIndividuInfo, new RecordItemIndex(119));
            repo.ApplicationUnderTest.TgnosDetailIndividu.MoveTo("427;5");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CbxCheckBox4' at 6;11.", repo.ApplicationUnderTest.Individu1.CbxCheckBox4Info, new RecordItemIndex(120));
            repo.ApplicationUnderTest.Individu1.CbxCheckBox4.Click("6;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.Individu1.TxtGewensteUurloonBrutoAspiraties' at 210;23.", repo.ApplicationUnderTest.Individu1.TxtGewensteUurloonBrutoAspiratiesInfo, new RecordItemIndex(121));
            repo.ApplicationUnderTest.Individu1.TxtGewensteUurloonBrutoAspiraties.MoveTo("210;23");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.Individu1.TxtGewensteUurloonBrutoAspiraties' at 218;15.", repo.ApplicationUnderTest.Individu1.TxtGewensteUurloonBrutoAspiratiesInfo, new RecordItemIndex(122));
            repo.ApplicationUnderTest.Individu1.TxtGewensteUurloonBrutoAspiraties.MoveTo("218;15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.Individu1.CbxCheckBox5' at 6;12.", repo.ApplicationUnderTest.Individu1.CbxCheckBox5Info, new RecordItemIndex(123));
            repo.ApplicationUnderTest.Individu1.CbxCheckBox5.MoveTo("6;12");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.BtnOpslaan' at 49;13.", repo.ApplicationUnderTest.Individu1.BtnOpslaanInfo, new RecordItemIndex(124));
            repo.ApplicationUnderTest.Individu1.BtnOpslaan.Click("49;13");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='\t\tEén of meerdere fouten hebben zich voorgedaan tijdens het opslaan van de gegevens.') on item 'ApplicationUnderTest.Individu1.TextEenOfMeerdereFoutenHebbenZich'.", repo.ApplicationUnderTest.Individu1.TextEenOfMeerdereFoutenHebbenZichInfo, new RecordItemIndex(125));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Individu1.TextEenOfMeerdereFoutenHebbenZichInfo, "Text", "\t\tEén of meerdere fouten hebben zich voorgedaan tijdens het opslaan van de gegevens.");
            
            // Start Dienstencheque
            Report.Log(ReportLevel.Info, "Section", "Start Dienstencheque", new RecordItemIndex(126));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.Dienstencheque' at 59;20.", repo.ApplicationUnderTest.Individu1.DienstenchequeInfo, new RecordItemIndex(127));
            repo.ApplicationUnderTest.Individu1.Dienstencheque.Click("59;20");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox9' at 207;10.", repo.ApplicationUnderTest.Individu1.CboComboBox9Info, new RecordItemIndex(128));
            repo.ApplicationUnderTest.Individu1.CboComboBox9.Click("207;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.OntvangtGeenUitkering' at 124;5.", repo.List1000.OntvangtGeenUitkeringInfo, new RecordItemIndex(129));
            repo.List1000.OntvangtGeenUitkering.Click("124;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox10' at 141;15.", repo.ApplicationUnderTest.Individu1.CboComboBox10Info, new RecordItemIndex(130));
            repo.ApplicationUnderTest.Individu1.CboComboBox10.Click("141;15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.GEENTewerkstellingBijEenAnderDCQBe' at 138;4.", repo.List1000.GEENTewerkstellingBijEenAnderDCQBeInfo, new RecordItemIndex(131));
            repo.List1000.GEENTewerkstellingBijEenAnderDCQBe.Click("138;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox11' at 139;17.", repo.ApplicationUnderTest.Individu1.CboComboBox11Info, new RecordItemIndex(132));
            repo.ApplicationUnderTest.Individu1.CboComboBox11.Click("139;17");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.Structureel' at 72;4.", repo.List1000.StructureelInfo, new RecordItemIndex(133));
            repo.List1000.Structureel.Click("72;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.CboComboBox12' at 108;15.", repo.ApplicationUnderTest.Individu1.CboComboBox12Info, new RecordItemIndex(134));
            repo.ApplicationUnderTest.Individu1.CboComboBox12.Click("108;15");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'List1000.NietBelangrijk' at 60;2.", repo.List1000.NietBelangrijkInfo, new RecordItemIndex(135));
            repo.List1000.NietBelangrijk.Click("60;2");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.PoetsenVanDeWoning' at 8;10.", repo.ApplicationUnderTest.Individu1.PoetsenVanDeWoningInfo, new RecordItemIndex(136));
            repo.ApplicationUnderTest.Individu1.PoetsenVanDeWoning.Click("8;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.UrenPerWeek' at 185;7.", repo.ApplicationUnderTest.Individu1.UrenPerWeekInfo, new RecordItemIndex(137));
            repo.ApplicationUnderTest.Individu1.UrenPerWeek.Click("185;7");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '30' with focus on 'ApplicationUnderTest.Individu1.UrenPerWeek'.", repo.ApplicationUnderTest.Individu1.UrenPerWeekInfo, new RecordItemIndex(138));
            repo.ApplicationUnderTest.Individu1.UrenPerWeek.PressKeys("30");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.LblMaandagVmVoorkeur' at Center.", repo.ApplicationUnderTest.Individu1.LblMaandagVmVoorkeurInfo, new RecordItemIndex(139));
            repo.ApplicationUnderTest.Individu1.LblMaandagVmVoorkeur.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.LblMaandagNmVoorkeur' at Center.", repo.ApplicationUnderTest.Individu1.LblMaandagNmVoorkeurInfo, new RecordItemIndex(140));
            repo.ApplicationUnderTest.Individu1.LblMaandagNmVoorkeur.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.LblDinsdagVmVoorkeur' at 73;11.", repo.ApplicationUnderTest.Individu1.LblDinsdagVmVoorkeurInfo, new RecordItemIndex(141));
            repo.ApplicationUnderTest.Individu1.LblDinsdagVmVoorkeur.Click("73;11");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.LblWoensdagVmVoorkeur' at 42;10.", repo.ApplicationUnderTest.Individu1.LblWoensdagVmVoorkeurInfo, new RecordItemIndex(142));
            repo.ApplicationUnderTest.Individu1.LblWoensdagVmVoorkeur.Click("42;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.LblDinsdagNmVoorkeur' at 92;12.", repo.ApplicationUnderTest.Individu1.LblDinsdagNmVoorkeurInfo, new RecordItemIndex(143));
            repo.ApplicationUnderTest.Individu1.LblDinsdagNmVoorkeur.Click("92;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.LblWoensdagNmVoorkeur' at 41;12.", repo.ApplicationUnderTest.Individu1.LblWoensdagNmVoorkeurInfo, new RecordItemIndex(144));
            repo.ApplicationUnderTest.Individu1.LblWoensdagNmVoorkeur.Click("41;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.LblDonderdagVmVoorkeur' at 35;12.", repo.ApplicationUnderTest.Individu1.LblDonderdagVmVoorkeurInfo, new RecordItemIndex(145));
            repo.ApplicationUnderTest.Individu1.LblDonderdagVmVoorkeur.Click("35;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.Individu1.LblDonderdagNmVoorkeur' at 36;10.", repo.ApplicationUnderTest.Individu1.LblDonderdagNmVoorkeurInfo, new RecordItemIndex(146));
            repo.ApplicationUnderTest.Individu1.LblDonderdagNmVoorkeur.MoveTo("36;10");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.LblVrijdagVmVoorkeur' at 18;16.", repo.ApplicationUnderTest.Individu1.LblVrijdagVmVoorkeurInfo, new RecordItemIndex(147));
            repo.ApplicationUnderTest.Individu1.LblVrijdagVmVoorkeur.Click("18;16");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.BtnOpslaan' at Center.", repo.ApplicationUnderTest.Individu1.BtnOpslaanInfo, new RecordItemIndex(148));
            repo.ApplicationUnderTest.Individu1.BtnOpslaan.Click();
            
            // Start Opmerkingen
            Report.Log(ReportLevel.Info, "Section", "Start Opmerkingen", new RecordItemIndex(149));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.Opmerkingen' at 67;16.", repo.ApplicationUnderTest.Individu1.OpmerkingenInfo, new RecordItemIndex(150));
            repo.ApplicationUnderTest.Individu1.Opmerkingen.Click("67;16");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.OpmerkingenBijFunctioneleRelevantie' at 579;98.", repo.ApplicationUnderTest.Individu1.OpmerkingenBijFunctioneleRelevantieInfo, new RecordItemIndex(151));
            repo.ApplicationUnderTest.Individu1.OpmerkingenBijFunctioneleRelevantie.Click("579;98");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'ApplicationUnderTest.Individu1.OpmerkingenBijFunctioneleRelevantie'.", repo.ApplicationUnderTest.Individu1.OpmerkingenBijFunctioneleRelevantieInfo, new RecordItemIndex(152));
            repo.ApplicationUnderTest.Individu1.OpmerkingenBijFunctioneleRelevantie.PressKeys("test");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Individu1.BtnOpslaan' at 51;18.", repo.ApplicationUnderTest.Individu1.BtnOpslaanInfo, new RecordItemIndex(153));
            repo.ApplicationUnderTest.Individu1.BtnOpslaan.Click("51;18");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='\t\tHet opslaan is voltooid.') on item 'ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooid'.", repo.ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooidInfo, new RecordItemIndex(154));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Individu1.TextHetOpslaanIsVoltooidInfo, "Text", "\t\tHet opslaan is voltooid.");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
