///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TGNOS
{
    public partial class Recording1
    {
    	
    	private TGNOSRepository myRepo = new TGNOSRepository();
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
           
        }

        public void searchIndividu(RepoItemInfo textInfo)
        {
            this.myRepo.TGNOS.OpzoekenIndividuStart.FamilienaamZoek.TextValue =  varLastName;
            this.myRepo.TGNOS.OpzoekenIndividuStart.VoornaamZoek.TextValue = varFirstName;
           
        }
        
        public void fillBasicInfo(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Basic Info", "Lastname from variable '$varLastName' with focus on 'textInfo'.", textInfo);
            this.myRepo.TGNOS.TbpgBasisInformatie.Familienaam.TextValue =  varLastName;
            Report.Log(ReportLevel.Info, "Basic Info", "Firstname from variable '$varFirstName' with focus on 'textInfo'.", textInfo);
            this.myRepo.TGNOS.TbpgBasisInformatie.Voornaam.TextValue =  varFirstName;
            Report.Log(ReportLevel.Info, "Basic Info", "Firstname from variable '$varRRNr' with focus on 'textInfo'.", textInfo);
            this.myRepo.TGNOS.TbpgBasisInformatie.INSZNummer.TextValue =  varRRNr;
            this.myRepo.TGNOS.TbpgBasisInformatie.Geboorteplaats.TextValue =  varBirthCity;
            this.myRepo.TGNOS.TbpgBasisInformatie.TextAsterisk.Focus();
            this.myRepo.TGNOS.TbpgBasisInformatie.TextAsterisk.TextValue =  varBirthDate;
       
           
        }
        
        public void fillSignalism()
        {
        	this.myRepo.TGNOS.TbpgSignalitiek.GsmNr.TextValue =  varMobile;
        	this.myRepo.TGNOS.TbpgSignalitiek.TelefoonnrThuis.TextValue =  varPhone;
        	this.myRepo.TGNOS.TbpgSignalitiek.Email.TextValue =  varEmail;
        	this.myRepo.TGNOS.TbpgSignalitiek.TxtStraat1.TextValue =  varStreet;	
        	this.myRepo.TGNOS.TbpgSignalitiek.Straat.TextValue =  varStraatNo;
        	this.myRepo.TGNOS.TbpgSignalitiek.Text2.TextValue =  varZipCode;
        }
        
        public void fillTaxPayroll()
        {
        	this.myRepo.TGNOS.TbpgFiskaal1.FiskSituatieDate.Focus(); 
        	this.myRepo.TGNOS.TbpgFiskaal1.FiskSituatieDate.TextValue = varTaxSituationDate;
        	this.myRepo.TGNOS.TbpgFiskaal1.MariageDate.Focus();
        	this.myRepo.TGNOS.TbpgFiskaal1.MariageDate.TextValue = varMarriageDate;      	
        	this.myRepo.TGNOS.TbpgFiskaal1.NaamEchtgenoot.TextValue = varLastNameSpouse;
        	this.myRepo.TGNOS.TbpgFiskaal1.VoornaamEchtgenoot.TextValue = varFirstNameSpouse;
        	this.myRepo.TGNOS.TbpgFiskaal1.GeboorteDatumEchtgenoot.Focus();
        	this.myRepo.TGNOS.TbpgFiskaal1.GeboorteDatumEchtgenoot.TextValue = varBirthDateSpouse;
        	this.myRepo.TGNOS.TbpgFiskaal1.IBAN.Focus();
        	this.myRepo.TGNOS.TbpgFiskaal1.IBAN.TextValue = varBankNumber;        	
        	this.myRepo.TGNOS.TbpgFiskaal1.InvaliditeitIndividuPercentage.TextValue = varIndividualDisability;
        	this.myRepo.TGNOS.TbpgFiskaal1.AantPersTenLasteValide.TextValue = varNoOfDependants;
        	this.myRepo.TGNOS.TbpgFiskaal1.AantPersTenLasteAndersvalide.TextValue = varNoOfDependantsDisability;
        	this.myRepo.TGNOS.TbpgFiskaal1.Aant65PlusPersTenLasteValide.TextValue = varNumberOf65plusDependants;
        	this.myRepo.TGNOS.TbpgFiskaal1.Aant65PlusTenLasteAndersvalide.TextValue = varNumberOf65plusDependantsDisability; 	
        	this.myRepo.TGNOS.TbpgFiskaal1.AantKindTenLasteValide.TextValue = varNoOfDependantChildren;
        	this.myRepo.TGNOS.TbpgFiskaal1.AantKindTenLasteAndersvalide.TextValue = varNoOfDependantChildrenDisability;
        }
        
        public void fillAspirations()
        {
        	
        
        }

    }
}
