///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TGNOS
{
    public partial class Recording1
    {
    	
    	private TGNOSRepository myRepo = new TGNOSRepository();
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
           
        }

        public void addRRNr(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varRRNr' with focus on 'textInfo'.", textInfo);
            this.myRepo.ApplicationUnderTest.OpzoekenIndividuStart.INSZNummer.TextValue =  varRRNr;
           
        }
        
        public void fillBasicInfo(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Basic Info", "Lastname from variable '$varLastName' with focus on 'textInfo'.", textInfo);
            this.myRepo.ApplicationUnderTest.TbpgBasisInformatie.Familienaam.TextValue =  varLastName;
            Report.Log(ReportLevel.Info, "Basic Info", "Firstname from variable '$varFirstName' with focus on 'textInfo'.", textInfo);
            this.myRepo.ApplicationUnderTest.TbpgBasisInformatie.Voornaam1.TextValue =  varFirstName;
            Report.Log(ReportLevel.Info, "Basic Info", "Firstname from variable '$varRRNr' with focus on 'textInfo'.", textInfo);
            this.myRepo.ApplicationUnderTest.TbpgBasisInformatie.INSZNummer1.TextValue =  varRRNr;
            this.myRepo.ApplicationUnderTest.TbpgBasisInformatie.Geboorteplaats.TextValue =  varBirthCity;
            this.myRepo.ApplicationUnderTest.TbpgBasisInformatie.TextAsterisk.Focus();
            this.myRepo.ApplicationUnderTest.TbpgBasisInformatie.TextAsterisk.TextValue =  varBirthDate;
       
           
        }
        
        public void fillSignalism()
        {
        	this.myRepo.ApplicationUnderTest.TbpgSignalitiek.GsmNr.TextValue =  varMobile;
        	this.myRepo.ApplicationUnderTest.TbpgSignalitiek.TelefoonnrThuis.TextValue =  varPhone;
        	this.myRepo.ApplicationUnderTest.TbpgSignalitiek.Email.TextValue =  varEmail;
        	this.myRepo.ApplicationUnderTest.TbpgSignalitiek.TxtStraat1.TextValue =  varStreet;	
        	this.myRepo.ApplicationUnderTest.TbpgSignalitiek.Straat.TextValue =  varStraatNo;
        	this.myRepo.ApplicationUnderTest.TbpgSignalitiek.Text2.TextValue =  varZipCode;
        }
        
        public void fillTaxPayroll()
        {
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.TextAsterisk1.TextValue = varTaxSituationDate;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.TextAsterisk2.TextValue = varMarriageDate;
        	
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.NaamEchtgenoOTE.TextValue = varLastNameSpouse;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.VoornaamEchtgenoOTE.TextValue = varFirstNameSpouse;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.TextAsterisk.TextValue = varBirthDateSpouse;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.IBAN.TextValue = varBankNumber;
        	
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.TextPercentInvaliditeitIndividu.TextValue = varIndividualDisability;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.AantPersTenLasteValide.TextValue = varNoOfDependants;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.TxtTextBox.TextValue = varNoOfDependantsDisability;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.Aant65PlusPersTenLasteValide.TextValue = varNumberOf65plusDependants;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.Aant65PlusTenLasteAndersvalide.TextValue = varNumberOf65plusDependantsDisability;
        		
        	
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.AantKindTenLasteValide.TextValue = varNoOfDependantChildren;
        	this.myRepo.ApplicationUnderTest.TbpgFiscaalVerloning.AantKindTenLasteAndersvalide.TextValue = varNoOfDependantChildrenDisability;
        }
        
        public void fillAspirations()
        {
        	
        
        }

    }
}
